root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./server.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "graphql", "graphqls"]
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = false
